update min macos to 10.8
Otherwise we get this error

```
2 warnings generated.
OBJCC	libavdevice/avfoundation.o
libavdevice/avfoundation.m:207:14: error: 'objectForKeyedSubscript:' is only available on macOS 10.8 or newer
      [-Werror,-Wunguarded-availability]
            [change[NSKeyValueChangeNewKey] integerValue];
             ^~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSDictionary.h:46:1: note:
      'objectForKeyedSubscript:' has been marked as being introduced in macOS 10.8 here, but the deployment target is macOS 10.7.0
- (nullable ObjectType)objectForKeyedSubscript:(KeyType)key API_AVAILABLE(macos(10.8), ios(6.0), watchos(2.0), tvos(9.0));
^
libavdevice/avfoundation.m:207:14: note: enclose 'objectForKeyedSubscript:' in an @available check to silence this warning
            [change[NSKeyValueChangeNewKey] integerValue];
             ^~~~~~
1 error generated.
make: *** [libavdevice/avfoundation.o] Error 1
```